Algoritmo "operador com descritivo"

Var

valor:real
minutos, excedente, minutosMes, pagar: inteiro
plano : caractere



Inicio


Escreval ("Quantos minutos utilizou: ")
leia(minutos)


Valor <- 50
Se minutos > 100 entao
valor <- valor + 2 * (minutos - 100)

Escreval("Valor Fatura = ", valor)
Escreval("Demonstrativo")
Escreval ("Fatura = R$50,00 ")
Escreva ("Excedente = ",minutos - 100)

FIMSE





Fimalgoritmo
